// Login Action Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

// Menu Action Types
export const MENU_GET_REQUEST = "MENU_GET_REQUEST";
export const MENU_GET_SUCCESS = "MENU_GET_SUCCESS";
export const MENU_GET_FAILURE = "MENU_GET_FAILURE";

// Submenu Action Types
export const SUBMENU_GET_REQUEST = "SUBMENU_GET_REQUEST";
export const SUBMENU_GET_SUCCESS = "SUBMENU_GET_SUCCESS";
export const SUBMENU_GET_FAILURE = "SUBMENU_GET_FAILURE";

// Home Banner Action Types
export const HOME_BANNER_GET_REQUEST = "HOME_BANNER_GET_REQUEST";
export const HOME_BANNER_GET_SUCCESS = "HOME_BANNER_GET_SUCCESS";
export const HOME_BANNER_GET_FAILURE = "HOME_BANNER_GET_FAILURE";

// All Product Action Types
export const ALL_PRODUCT_GET_REQUEST = "ALL_PRODUCT_GET_REQUEST";
export const ALL_PRODUCT_GET_SUCCESS = "ALL_PRODUCT_GET_SUCCESS";
export const ALL_PRODUCT_GET_FAILURE = "ALL_PRODUCT_GET_FAILURE";

// Trading Product Action Types
export const TRADING_PRODUCT_GET_REQUEST = "TRADING_PRODUCT_GET_REQUEST";
export const TRADING_PRODUCT_GET_SUCCESS = "TRADING_PRODUCT_GET_SUCCESS";
export const TRADING_PRODUCT_GET_FAILURE = "TRADING_PRODUCT_GET_FAILURE";

// Best Service Action Types
export const BEST_SERVICE_GET_REQUEST = "BEST_SERVICE_GET_REQUEST";
export const BEST_SERVICE_GET_SUCCESS = "BEST_SERVICE_GET_SUCCESS";
export const BEST_SERVICE_GET_FAILURE = "BEST_SERVICE_GET_FAILURE";

// Video Action Types
export const VIDEO_GET_REQUEST = "VIDEO_GET_REQUEST";
export const VIDEO_GET_SUCCESS = "VIDEO_GET_SUCCESS";
export const VIDEO_GET_FAILURE = "VIDEO_GET_FAILURE";

// Contact Us Action Types
export const FETCH_SUBMENUS_REQUEST = "FETCH_SUBMENUS_REQUEST";
export const FETCH_SUBMENUS_SUCCESS = "FETCH_SUBMENUS_SUCCESS";
export const FETCH_SUBMENUS_FAILURE = "FETCH_SUBMENUS_FAILURE";

// addressActionTypes.ts
export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAILURE = "CREATE_ADDRESS_FAILURE";

// Get
export const GET_ADDRESSES_REQUEST = "GET_ADDRESSES_REQUEST";
export const GET_ADDRESSES_SUCCESS = "GET_ADDRESSES_SUCCESS";
export const GET_ADDRESSES_FAILURE = "GET_ADDRESSES_FAILURE";

// PUT (Update Address)
export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";

// DELETE (Remove Address)
export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

// ADD to Wishlist
export const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAILURE = "ADD_WISHLIST_FAILURE";

// REMOVE from Wishlist
export const REMOVE_WISHLIST_REQUEST = "REMOVE_WISHLIST_REQUEST";
export const REMOVE_WISHLIST_SUCCESS = "REMOVE_WISHLIST_SUCCESS";
export const REMOVE_WISHLIST_FAILURE = "REMOVE_WISHLIST_FAILURE";

// GET Wishlist
export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";

// Search Products
export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILURE = "SEARCH_PRODUCT_FAILURE";


// Home TShirt Products
export const GET_HOMETSHIRT_REQUEST = "GET_HOMETSHIRT_REQUEST";
export const GET_HOMETSHIRT_SUCCESS = "GET_HOMETSHIRT_SUCCESS";
export const GET_HOMETSHIRT_FAILURE = "GET_HOMETSHIRT_FAILURE";

// Trending Products
export const GET_TRENDING_PRODUCTS_REQUEST = "GET_TRENDING_PRODUCTS_REQUEST";
export const GET_TRENDING_PRODUCTS_SUCCESS = "GET_TRENDING_PRODUCTS_SUCCESS";
export const GET_TRENDING_PRODUCTS_FAILURE = "GET_TRENDING_PRODUCTS_FAILURE";

// Add to Cart
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

// Delete from Cart
export const DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST";
export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_FAILURE = "DELETE_FROM_CART_FAILURE";

// Get Cart
export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

// redux/actiontype/cartActionTypes.ts

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";


// Gallery action types
export const GET_GALLERY_REQUEST = "GET_GALLERY_REQUEST";
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAILURE = "GET_GALLERY_FAILURE";



// Order action types
export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

// Get Orders action types
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

// Update Order action types
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

// Get All Orders action types
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";
