// Login Action Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";

// Menu Action Types
export const MENU_GET_REQUEST = "MENU_GET_REQUEST";
export const MENU_GET_SUCCESS = "MENU_GET_SUCCESS";
export const MENU_GET_FAILURE = "MENU_GET_FAILURE";

// Submenu Action Types
export const SUBMENU_GET_REQUEST = "SUBMENU_GET_REQUEST";
export const SUBMENU_GET_SUCCESS = "SUBMENU_GET_SUCCESS";
export const SUBMENU_GET_FAILURE = "SUBMENU_GET_FAILURE";

// Home Banner Action Types
export const HOME_BANNER_GET_REQUEST = "HOME_BANNER_GET_REQUEST";
export const HOME_BANNER_GET_SUCCESS = "HOME_BANNER_GET_SUCCESS";
export const HOME_BANNER_GET_FAILURE = "HOME_BANNER_GET_FAILURE";


// All Product Action Types
export const ALL_PRODUCT_GET_REQUEST = "ALL_PRODUCT_GET_REQUEST";
export const ALL_PRODUCT_GET_SUCCESS = "ALL_PRODUCT_GET_SUCCESS";
export const ALL_PRODUCT_GET_FAILURE = "ALL_PRODUCT_GET_FAILURE";

